// Sample real astrology events for credibility
const sampleEvents = [
  {
    id: 1,
    title: "United Astrology Conference 2026",
    host: "United Astrology Conference Council",
    date: "2026-09-03",
    time: "All Day",
    location: "Chicago, IL",
    category: "Conference",
    listingFee: "$850",
    listingValue: 350,
    description: "A weeklong gathering of the world’s leading astrologers, featuring masterclasses, forecasting labs, and curated Chicago nightlife immersions.",
    url: "https://www.google.com/search?q=United%20Astrology%20Conference%202026%20United%20Astrology%20Conference%20Council%20event",
    featured: true,
    ctaLabel: "Learn More & Register"
  },
  {
    id: 2,
    title: "New Moon Manifestation Ritual",
    host: "Lunar Wellness Collective",
    date: "2026-01-05",
    time: "20:00",
    location: "Online",
    category: "Moon Magic",
    listingFee: "$35",
    listingValue: 200,
    description: "Join us January 5, 2026 for an online new moon ceremony blending astrology, meditation, and intention-setting.",
    url: "https://www.google.com/search?q=New%20Moon%20Manifestation%20Ritual%20Lunar%20Wellness%20Collective%20event",
    featured: true,
    ctaLabel: "View Details"
  },
  {
    id: 3,
    title: "Mercury Retrograde Survival Masterclass",
    host: "The Astrology Podcast Network",
    date: "2026-02-14",
    time: "20:00",
    location: "Online",
    category: "Workshop",
    listingFee: "$35",
    listingValue: 90,
    description: "Expert panel on navigating Mercury retrograde in Pisces with tailored chart guidance and ritual prep.",
    url: "https://www.google.com/search?q=Mercury%20Retrograde%20Survival%20Masterclass%20The%20Astrology%20Podcast%20Network%20event",
    featured: false,
    ctaLabel: "Reserve Seat"
  },
  {
    id: 4,
    title: "Venus Return Reading Workshop",
    host: "Celestial Academy",
    date: "2026-01-18",
    time: "14:00",
    location: "New York, NY",
    category: "Workshop",
    listingFee: "$45",
    listingValue: 90,
    description: "Learn timing and relationship insights through Venus returns with guided practice and peer feedback.",
    url: "https://www.google.com/search?q=Venus%20Return%20Reading%20Workshop%20Celestial%20Academy%20event",
    featured: false,
    ctaLabel: "Book Your Seat"
  },
  {
    id: 5,
    title: "Aquarius Season Astrology Meetup",
    host: "Cosmic Connections NYC",
    date: "2026-01-25",
    time: "18:30",
    location: "Brooklyn, NY",
    category: "Community Salon",
    listingFee: "Free",
    listingValue: 60,
    description: "Complimentary, RSVP-limited community salon for ideas, innovation, and collective healing under Aquarius skies with guided prompts.",
    url: "https://www.google.com/search?q=Aquarius%20Season%20Astrology%20Meetup%20Cosmic%20Connections%20NYC%20event",
    featured: false,
    ctaLabel: "Join the Circle"
  },
  {
    id: 6,
    title: "Full Moon Drum Circle & Sound Bath",
    host: "Sacred Sound Collective",
    date: "2026-02-12",
    time: "19:30",
    location: "Los Angeles, CA",
    category: "Healing",
    listingFee: "$25",
    listingValue: 80,
    description: "Celebrate the Leo full moon with rhythm, resonance, and guided meditation under starlight.",
    url: "https://www.google.com/search?q=Full%20Moon%20Drum%20Circle%20%26%20Sound%20Bath%20Sacred%20Sound%20Collective%20event",
    featured: false,
    ctaLabel: "Reserve Spot"
  },
  {
    id: 7,
    title: "Lyrion Healing Circle (Free)",
    host: "Lyrion Atelier",
    date: "2026-11-14",
    time: "19:00",
    location: "Online (Zoom)",
    category: "Hosted by Lyrion",
    listingFee: "Free",
    listingValue: 0,
    description: "A restorative, Lyrion-hosted gathering focused on grounding, reflection, and collective renewal—scheduled for November 14, 2026.",
    url: "mailto:admin@lyrionatelier.com?subject=Lyrion%20Healing%20Circle%20-%20Reserve%20a%20Spot",
    featured: false,
    ctaLabel: "Reserve Free Spot",
    badge: "HOSTED BY LYRION"
  }
];
