#!/usr/bin/env node
/**
 * Publish the house engine's approved journal articles.
 *
 * Reads data/codex-queue/YYYY-MM-DD-slug.md (front matter: title,
 * description, date, status: approved; then plain paragraphs) and, for each
 * approved article dated today or earlier (London time):
 *   - writes codex/<slug>.html in the Codex design, with its own title, meta
 *     description, canonical URL and Article structured data,
 *   - lists it in the "From the journal" block of codex.html,
 *   - adds it to sitemap.xml.
 * Pages for articles that have left the queue are removed again.
 *
 * The queue is written by the engine, so this script never fails on its
 * content: a file it cannot read is reported and skipped.
 *
 *   node scripts/publish-codex.mjs [--queue dir] [--root dir] [--today YYYY-MM-DD]
 */
import { readFile, writeFile, readdir, mkdir, unlink } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { REPO_ROOT, houseCore } from './lib/catalog.mjs';

const SITE = 'https://lyrionatelier.com';
const GENERATED = '<meta name="lyrion:generated" content="codex-queue">';
const LIST_START = '<!-- codex-journal:start (generated by scripts/publish-codex.mjs) -->';
const LIST_END = '<!-- codex-journal:end -->';
const MAP_START = '<!-- codex-articles:start (generated by scripts/publish-codex.mjs) -->';
const MAP_END = '<!-- codex-articles:end -->';

const args = process.argv.slice(2);
const opt = (name, fallback) => {
  const i = args.indexOf(name);
  return i !== -1 && args[i + 1] ? args[i + 1] : fallback;
};
const ROOT = path.resolve(opt('--root', REPO_ROOT));
const QUEUE = path.resolve(opt('--queue', path.join(ROOT, 'data', 'codex-queue')));
const TODAY = opt('--today', houseCore.todayISO());

const esc = (s) => String(s ?? '')
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/** Minimal front matter: `key: value` lines between --- fences. */
export function parseArticle(raw, filename) {
  const m = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/.exec(raw);
  if (!m) throw new Error('no front matter');
  const meta = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = /^([A-Za-z_]+)\s*:\s*(.*)$/.exec(line);
    if (!kv) continue;
    let v = kv[2].trim();
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1);
    meta[kv[1].toLowerCase()] = v;
  }
  const name = /^(\d{4}-\d{2}-\d{2})-([a-z0-9]+(?:-[a-z0-9]+)*)\.md$/.exec(filename);
  if (!name) throw new Error('file name must be YYYY-MM-DD-slug.md');
  if (!meta.title) throw new Error('title is missing');
  if (!meta.description) throw new Error('description is missing');
  const date = meta.date && houseCore.validDate(String(meta.date).slice(0, 10)) ? String(meta.date).slice(0, 10) : name[1];
  const paragraphs = m[2].split(/\r?\n\s*\r?\n/).map((p) => p.replace(/\s*\r?\n\s*/g, ' ').trim()).filter(Boolean);
  if (!paragraphs.length) throw new Error('the article has no paragraphs');
  return {
    slug: name[2],
    title: meta.title,
    description: meta.description,
    date,
    status: String(meta.status || '').toLowerCase(),
    paragraphs,
  };
}

function longDate(iso) {
  return new Date(`${iso}T12:00:00Z`).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'UTC' });
}

function shell(codexHtml) {
  const header = codexHtml.slice(codexHtml.indexOf('<header class="site-header"'), codexHtml.indexOf('</header>') + '</header>'.length);
  const footer = codexHtml.slice(codexHtml.indexOf('<footer class="footer">'), codexHtml.indexOf('</footer>') + '</footer>'.length);
  return { header, footer };
}

function articlePage(a, { header, footer }) {
  const url = `${SITE}/codex/${a.slug}`;
  const ld = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: a.title,
    description: a.description,
    datePublished: a.date,
    dateModified: a.date,
    mainEntityOfPage: url,
    url,
    image: `${SITE}/images/lyrion-logo.png`,
    author: { '@type': 'Organization', name: 'Lyrīon Atelier', url: SITE },
    publisher: {
      '@type': 'Organization',
      name: 'Lyrīon Atelier',
      legalName: 'LYRION LTD',
      url: SITE,
      logo: { '@type': 'ImageObject', url: `${SITE}/images/lyrion-logo.png` },
    },
  };
  const crumbs = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: SITE },
      { '@type': 'ListItem', position: 2, name: 'The Codex', item: `${SITE}/codex` },
      { '@type': 'ListItem', position: 3, name: a.title, item: url },
    ],
  };
  const body = a.paragraphs.map((p) => `            <p class="codex-event-copy">${esc(p)}</p>`).join('\n');
  return `<!DOCTYPE html>
<html lang="en">
<head>
<script src="/js/analytics.js"></script>
  <meta charset="UTF-8">
  ${GENERATED}
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0, user-scalable=yes">
  <title>${esc(a.title)} | The Codex | Lyrīon Atelier</title>
  <meta name="description" content="${esc(a.description)}">
  <meta property="og:title" content="${esc(a.title)}">
  <meta property="og:description" content="${esc(a.description)}">
  <meta property="og:image" content="${SITE}/images/lyrion-logo.png">
  <meta property="og:type" content="article">
  <meta property="og:url" content="${url}">
  <meta property="article:published_time" content="${a.date}">
  <meta name="twitter:card" content="summary_large_image">
  <link rel="canonical" href="${url}">
  <link rel="icon" type="image/png" href="/images/favicon/favicon.png">
  <link rel="stylesheet" href="/styles/design-system.css">
  <link rel="stylesheet" href="/css/type-scale.css">
  <link rel="stylesheet" href="/css/style.css">
  <link rel="stylesheet" href="/css/button-fixes.css?v=2">
  <link rel="stylesheet" href="/css/polish.css">
  <link rel="stylesheet" href="/css/restoration.css">
  <link rel="stylesheet" href="/css/house.css">
<script type="application/ld+json">
${JSON.stringify(ld, null, 2)}
</script>
<script type="application/ld+json">
${JSON.stringify(crumbs, null, 2)}
</script>
</head>
<body>
${header}

  <a class="skip-to-content" href="#main-content">Skip to main content</a>
<main id="main-content">
    <div class="codex-page-header">
      <p class="codex-article-back"><a href="/codex">The Codex</a></p>
      <h1>${esc(a.title)}</h1>
      <p>${esc(a.description)}</p>
    </div>

    <section class="codex-timeline-section">
      <div class="codex-timeline">
        <article class="codex-entry codex-article">
          <div class="codex-date">
            <time class="codex-date-primary" datetime="${a.date}">${longDate(a.date)}</time>
          </div>
          <div class="codex-body">
${body}
          </div>
        </article>
      </div>
    </section>
    <div class="codex-cta-row" style="text-align:center;padding:2rem 1rem 1rem;">
      <a href="/shop" class="btn btn--primary">Browse the Shop</a>
      <a href="/oracle" class="btn btn--secondary" style="margin-left:1rem;">Book a Reading</a>
    </div>
  </main>

  ${footer}

  <script src="/js/products.js" defer></script>
  <script src="/js/cart.js" defer></script>
  <script src="/js/main.js" defer></script>
</body>
</html>
`;
}

function journalBlock(articles) {
  if (!articles.length) return `${LIST_START}\n    ${LIST_END}`;
  const items = articles.map((a) => `        <article class="codex-entry" role="listitem" data-journal="${a.slug}">
          <div class="codex-date">
            <time class="codex-date-primary" datetime="${a.date}">${longDate(a.date)}</time>
          </div>
          <div class="codex-body">
            <h3 class="codex-event-title"><a href="/codex/${a.slug}">${esc(a.title)}</a></h3>
            <p class="codex-event-copy">${esc(a.description)}</p>
          </div>
        </article>`).join('\n');
  return `${LIST_START}
    <section class="codex-timeline-section codex-journal" aria-labelledby="codex-journal-heading">
      <h2 class="codex-journal-heading" id="codex-journal-heading">From the journal</h2>
      <div class="codex-timeline" role="list">
${items}
      </div>
    </section>
    ${LIST_END}`;
}

function sitemapBlock(articles) {
  const urls = articles.map((a) => `  <url>
    <loc>${SITE}/codex/${a.slug}</loc>
    <lastmod>${a.date}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.6</priority>
  </url>`).join('\n');
  return `${MAP_START}\n${urls}${urls ? '\n' : ''}  ${MAP_END}`;
}

function replaceBlock(text, start, end, block, insertBefore) {
  const i = text.indexOf(start);
  const j = text.indexOf(end);
  if (i !== -1 && j !== -1) return text.slice(0, i) + block + text.slice(j + end.length);
  const k = text.lastIndexOf(insertBefore);
  if (k === -1) throw new Error(`cannot place the generated block: "${insertBefore}" not found`);
  return `${text.slice(0, k)}${block}\n${text.slice(k)}`;
}

export async function publish() {
  const published = [];
  const skipped = [];
  const files = existsSync(QUEUE) ? (await readdir(QUEUE)).filter((f) => f.endsWith('.md')).sort() : [];
  for (const file of files) {
    try {
      const a = parseArticle(await readFile(path.join(QUEUE, file), 'utf8'), file);
      if (a.status !== 'approved') { skipped.push(`${file}: status is "${a.status || 'missing'}", not approved`); continue; }
      if (a.date > TODAY) { skipped.push(`${file}: dated ${a.date}, waiting until then`); continue; }
      if (published.some((p) => p.slug === a.slug)) { skipped.push(`${file}: slug "${a.slug}" already published from another file`); continue; }
      published.push(a);
    } catch (err) {
      skipped.push(`${file}: ${err.message}`);
    }
  }
  published.sort((x, y) => (x.date < y.date ? 1 : x.date > y.date ? -1 : x.slug.localeCompare(y.slug)));

  const codexPath = path.join(ROOT, 'codex.html');
  const codexHtml = await readFile(codexPath, 'utf8');
  const parts = shell(codexHtml);
  const outDir = path.join(ROOT, 'codex');
  await mkdir(outDir, { recursive: true });
  const keep = new Set(published.map((a) => `${a.slug}.html`));
  for (const a of published) await writeFile(path.join(outDir, `${a.slug}.html`), articlePage(a, parts), 'utf8');
  for (const f of await readdir(outDir)) {
    if (!f.endsWith('.html') || keep.has(f)) continue;
    const html = await readFile(path.join(outDir, f), 'utf8');
    if (html.includes(GENERATED)) await unlink(path.join(outDir, f));
  }

  const nextCodex = replaceBlock(codexHtml, LIST_START, LIST_END, journalBlock(published), '<div class="codex-cta-row"');
  if (nextCodex !== codexHtml) await writeFile(codexPath, nextCodex, 'utf8');

  const sitemapPath = path.join(ROOT, 'sitemap.xml');
  const sitemap = await readFile(sitemapPath, 'utf8');
  const nextMap = replaceBlock(sitemap, MAP_START, MAP_END, sitemapBlock(published), '</urlset>');
  if (nextMap !== sitemap) await writeFile(sitemapPath, nextMap, 'utf8');

  return { published, skipped };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { published, skipped } = await publish();
  console.log(`Codex: ${published.length} article(s) published.`);
  for (const a of published) console.log(`  /codex/${a.slug}  ${a.date}  ${a.title}`);
  for (const s of skipped) console.warn(`  skipped ${s}`);
}
